apiVersion: v1
kind: Secret
metadata:
  name: budget-secrets
  namespace: budget-app
type: Opaque
stringData:
  DB_PASSWORD: "super-secret-password-123"
  DB_HOST: "prod-db-cluster.internal"
  DB_USER: "admin_budget"
  DB_PORT: "5432"
  API_KEY: "ark-987-xyz-secret-key"
